version: '2.1'
orbs:
  maven: circleci/maven@1.3.0
executors:
  machine_executor_amd64:
    machine:
      image: ubuntu-2204:2024.11.1
    environment:
      architecture: "amd64"
      platform: "linux/amd64"
workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: machine_executor_amd64