package io.github.arun0009.idempotent.core.aspect;

/**
 * Validates idempotency keys received from an HTTP request header.
 *
 * <p>The annotation aspect invokes this validator only when the idempotency key is obtained from
 * the configured request header. Keys resolved from method parameters or generated by the aspect
 * are not validated automatically.</p>
 */
public interface IdempotencyKeyValidator {

    IdempotencyKeyValidator NOOP = key -> {};

    /**
     * Validates an idempotency key received from the request.
     *
     * @param key the unscoped value of the configured HTTP header
     * @throws RuntimeException when the key is invalid
     */
    void validate(String key);
}
